### ISSUE TITLE
Feature suggestion: remote working

### ISSUE THREAD

**Issue by jonathanknowles** [erkmos/haskell-companies#10]
From experience, whenever a new Haskell position is advertised, one of the most common questions asked is whether or not the company allows remote working (or has a culture that encourages remote working).

Perhaps we could add one or more columns to the table to indicate:
* whether or not team members are remote from one another;
* in which range of time zones a team operates.

**Comment by erkmos** [comment]
Hi, thanks for the suggestion. When you mention it; I've seen the same thing. Someone always seems to asks about that on Reddit hiring posts. I think it makes sense to at least add whether they support remote. Maybe I can shoehorn the timezone data into the locations column if the company is fully remote, don't really have the timezone data for any of these companies though.

**Comment by kanishka-azimi** [comment]
I would close this, leave identifying the timezones up to the job ad or company's website. Should try to keep the effort in keeping this list active and up to date to a minimum. I see this list as the launching point to find more information

**Comment by erkmos** [comment]
Ended up adding one column to just indicate whether they support remote or not, so closing this issue
