### ISSUE TITLE
Add QBayLogic and Driebit

### ISSUE THREAD

**Issue by noughtmare** [erkmos/haskell-companies#126]
QBayLogic:

 * Website: https://qbaylogic.com/
 * Location: The Netherlands, Enschede
 * Sector: Hardware description (they are the creators of [CλaSH](https://clash-lang.org/))
 * Source: https://www.reddit.com/r/haskell/comments/d3cwmi/job_qbaylogic_is_hiring/ (this position has already been filled)
 * Remote: No

driebit:

 * Website: https://www.driebit.nl/
 * Location: The Netherlands, Amsterdam
 * Sector: Web applications
 * Source: [they put an ad in Haskell Weekly issue 181](https://haskellweekly.news/issue/181.html)
 * Remote: No

**Comment by erkmos** [comment]
Added. Thanks for the update
