### ISSUE TITLE
"JAPAN MORGAN" isn't the name of that company

### ISSUE THREAD

**Issue by cartazio** [erkmos/haskell-companies#135]
:) 
- original job poster

**Comment by anacrolix** [comment]
herp 🤣

**Comment by erkmos** [comment]
Thanks for noticing that. Must've happened when I cleaned up country codes 🤣

**Comment by cartazio** [comment]
I’m still the right contact for that team amusingly ;)

Glad I could help. I thought it was a funny typo too. Forgot how I got to
this repo ;)
