### ISSUE TITLE
Add other lists

### ISSUE THREAD

**Issue by lucas-deangelis** [erkmos/haskell-companies#137]
There's at least two other lists like that, that are referenced by the [F# list](https://github.com/Kavignon/fsharp-companies):

- [Companies using Elm](https://github.com/jah2488/elm-companies)
- [Companies using Elixir](https://github.com/beam-community/elixir-companies)

While these projects do not look exactly the same as this one, I think it would be great if they were added here.

**Comment by erkmos** [comment]
Thanks, I created a new section for all these lists
