### ISSUE TITLE
Add Southern Exposure Seed Exchange

### ISSUE THREAD

**Issue by prikhi** [erkmos/haskell-companies#140]
We use Haskell for our eCommerce website and various scripts/services:

* Website: https://www.southernexposure.com/
* Github: https://github.com/Southern-Exposure-Seed-Exchange/ & https://github.com/Southern-Exposure-Seed-Exchange/southernexposure.com
* Location: Mineral, Virginia, USA
* Sector: eCommerce, agriculture, gardening, farming
* Source: GitHub. Also, I built the website :stuck_out_tongue: 
* Remote: No

**Comment by erkmos** [comment]
Added, thanks!
