### ISSUE TITLE
Hiring column

### ISSUE THREAD

**Issue by kanishka-azimi** [erkmos/haskell-companies#15]
I mentioned this briefly on Reddit a while back. Since this involves volunteer effort, I would skip the hiring column. People won't want to keep synchronizing it with their status, and I generally get the sense that most are willing to hire senior devs. So hiring really means actively hiring less experienced people. I think it is okay to ask readers of the list to follow a link to the company's site to determine if they are hiring currently.

**Comment by erkmos** [comment]
Yeah, I have been thinking about this as well. It's a lot of work to keep the hiring status of each company up to date.

**Comment by kanishka-azimi** [comment]
Maybe in the future, it could become "channel for job adverts", with options like "haskell reddit, functionaljobs, company website, ..."
