### ISSUE TITLE
link checker results - dead links

### ISSUE THREAD

**Issue by kanishka-azimi** [erkmos/haskell-companies#154]
Advancedtelematic - part of Here

https://chordify.homerun.com/ - moved

Hihenry

http://www.metrix-frs.de/

http://www.thoughtleadr.com/

(Brought to you by drlinkcheck (: )

**Comment by kanishka-azimi** [comment]
@stevana - should we update ats to link to Here?

**Comment by stevana** [comment]
Sure.

**Comment by kanishka-azimi** [comment]
@rubenmoor can we delete metrix?

**Comment by kanishka-azimi** [comment]
Metrix frs went dark in 2019: https://web.archive.org/web/2018*/metrix-frs.de

**Comment by kanishka-azimi** [comment]
Thiughtleadr notes here: https://github.com/erkmos/haskell-companies/pull/155

**Comment by kanishka-azimi** [comment]
should we redirect haskell companies list to accenture or remove the entry for thoughtleadr? @shakakai

**Comment by Shakakai** [comment]
> should we redirect haskell companies list to accenture or remove the entry for thoughtleadr? @Shakakai

You can remove the entry.
