### ISSUE TITLE
Jotron have removed almost all Haskell

### ISSUE THREAD

**Issue by yobson** [erkmos/haskell-companies#212]
It's sad but true. To increase their bus factor, Jotron AS have basically removed all their Haskell code.

**Comment by ulidtko** [comment]
Any source reference?

**Comment by yobson** [comment]
I work there. I also said we shouldn't be added to the list in the first place

**Comment by ulidtko** [comment]
Right, #172.
I'd let @erkmos decide the removal

**Comment by erkmos** [comment]
Since @yobson is basically the original source of it being added to the list at all, I have gone ahead and just removed the company from the list. Thanks for the update!
