### ISSUE TITLE
Best GitHub/Blog/Reddit contributions column

### ISSUE THREAD

**Issue by kanishka-azimi** [erkmos/haskell-companies#38]
A field with links highlighting either their direct work or work of their employees.

**Comment by erkmos** [comment]
Thanks for your idea. But I think this is a bit subjective, also I'd prefer keeping the list simple as there is less information to keep up-to-date that way. 🙂

**Comment by kanishka-azimi** [comment]
Thanks for considering. Yes, maintainability should trump usually.
