### ISSUE TITLE
Encourage Haskell light companies

### ISSUE THREAD

**Issue by kanishka-azimi** [erkmos/haskell-companies#39]
In the interest of growing the number companies thar have full time Haskellers, it might be useful to have a second table of "Haskell light" companies? We could encourage companies that have developers using Haskell at least 25% of their time to publicize themselves there. Some of those companies may eventually flip into joining the main table over time, most will probably serve as training ground for emerging Haskellers, but find it too hard to overcome past inertia generally.

**Comment by erkmos** [comment]
Good idea. This might be worthwhile, but I don't have that information for a single company currently on the list.

**Comment by kanishka-azimi** [comment]
If you start the empty table, I can start sending companies as I run across them. I suspect College Vine is one example.

**Comment by kanishka-azimi** [comment]
https://www.reddit.com/r/haskell/comments/5pzzvh/ann_bartlett_a_simple_jenkins_commandline_client/
 - Nike

**Comment by kanishka-azimi** [comment]
Draper labs - https://www.theladders.com/job/security-programmer-charles-stark-draper-laboratory-cambridge-ma_35780589

Akamai probably has something, but I didn't want to sift through their job site.

**Comment by kanishka-azimi** [comment]
Zolando mentions on Reddit most of their existing code is Scala, but Haskell is welcome, so probably should be in "light" table

**Comment by kanishka-azimi** [comment]
Thanks generally for maintaining this list.

I will close this issue and the other one, to not swamp you with minor edits. Feel free to reopen later if you want.
