### ISSUE TITLE
problems with canadian companies mentioned

### ISSUE THREAD

**Issue by functor-soup** [erkmos/haskell-companies#4]
Stytch site is broken
The other one located in Ottawa(Stilo) has no mention of Haskell in their software engineer (or full stack developer) position

**Comment by erkmos** [comment]
Thanks. The original source for Stytch was https://www.reddit.com/r/haskell/comments/5pan74/looking_for_haskell_companies_outside_usa/dcwwap4/

Stilo one is based on https://www.reddit.com/r/haskell/comments/5pan74/looking_for_haskell_companies_outside_usa/dcs45gh/

Mario Blažević (Stilo International plc; mblazevic@stilo.com) seems to be on the Haskell Prime commitee https://wiki.haskell.org/Language/HaskellPrime

I will remove Stytch for now and see if I can find any proof that Stilo is using haskell

**Comment by erkmos** [comment]
/u/blamario on reddit confirmed that they're still using Haskell at Stilo, will keep them on list for now.
