### ISSUE TITLE
Potential update

### ISSUE THREAD

**Issue by sigrlami** [erkmos/haskell-companies#5]
Here is also a list I have https://github.com/sigrlami/commercialhaskell/blob/master/active.csv  

Types of work:
- RD - research&development
- PR - product
- IP - in-house product
- CO - consulting

This not necessarily means it's only way company works. Many have inner products, but this key describes a type of work that presumably prevails.

**Comment by erkmos** [comment]
Cool, another list! Maybe it makes sense to collaborate on this?

Yeah, trying to describe some of the larger companies with just an acronym or "sector name" isn't particularly accurate, I have that same problem with my list. But at least it gives some indication.

**Comment by sigrlami** [comment]
@erkmos I can collaborate on your list, probably better to set it here, maybe update format and set of fields. I initially used also markdown, but CSV is filterable on Github and you can use this information elsewhere. Had an idea to set simple website.

**Comment by kanishka-azimi** [comment]
A google form/sheet might get more entries as people could submit from their phone, but this probably is easier for people trying to search for this page or browse the list.

I would stay in markdown over csv to be able to have cleaner hyperlinks (assume you can't make words hyperlinked in github CSV view)

**Comment by ashishsc** [comment]
A sheet would also allow you to easily filter by city / remoteOk etc.

**Comment by kanishka-azimi** [comment]
I think the cosmos site is nice. Regarding csv, maybe storing the source data in csv, so that cosmos and here can use the same file, but add a shell script in this repo to regenerate markdown table and have the person merging a given PR be in charge of rerunning csv -> markdown regenerate. That would keep the discoverability of this repo, and maintain low effort to contribute/update, and let cosmos keep building out more advanced analysis

**Comment by sigrlami** [comment]
@kanishka-azimi new update with self reporting coming. Unfortunately, leaving users in charge of regeneration not a good idea. Some analytics already here https://haskellcosm.com/analysis.html

Leave your comments in relevant repo for further discussion.
