### ISSUE TITLE
Remote work updates

### ISSUE THREAD

**Issue by satenndrra** [erkmos/haskell-companies#53]
Hello,

Thanks for putting this list together!

While researching these companies I noticed that a few now include remote-work option (see links alongside company names). We could probably update the remote column in the sheet with this data.

**alphasheets** (remote acceptable for contractors)
https://michael-gao-q5ib.squarespace.com/jobs/

**vacation-labs** (remote acceptable for haskell opening)
http://www.vacationlabs.com/we-are-hiring/software-engineer-haskell/

**clearmatics** (under header "Where we work")
https://www.clearmatics.com/careers/

**kadena**  (instance of a job posting with remote option available)
https://www.reddit.com/r/haskell/comments/7uuq0z/kadena_is_hiring_haskell_developers/

**lumi** (Engineering and Other jobs tagged REMOTE)
https://www.lumi.com/jobs

**obsidian-systems** (instance of past job posting with remote option available)
https://www.reddit.com/r/haskell/comments/49jjff/haskell_opportunities_at_obsidian_systems/

**superpowers-corp** (under WE ARE HIRING, remote considered on a case by case basis)
https://www.superpowerscorp.com/

**tripshot** (remote accepted but eligibility to work in the US needed)
https://www.tripshot.com/hiring/

**tweag** (hackernews job posting and tweag blog post mention remote acceptable)
https://news.ycombinator.com/item?id=16496787
https://www.tweag.io/posts/2018-02-08-internships.html

**Comment by erkmos** [comment]
Thanks! I added these

**Comment by satenndrra** [comment]
@erkmos You're welcome!
