### ISSUE TITLE
Add last updated column, purge stale

### ISSUE THREAD

**Issue by kanishka-azimi** [erkmos/haskell-companies#70]
Manually purge all entries that haven't been updated for a year, to prevent accumulating stale data. Note this rule prominently at the top of the readme

**Comment by ocramz** [comment]
However I'd be careful in removing companies because they might still be using the language even if they don't advertise it in new job ads.

**Comment by erkmos** [comment]
I think purging after one year seems a bit harsh, it's not always possible to get first-hand accounts on whether they still use the language or not. It's an interesting idea though

**Comment by kanishka-azimi** [comment]
Okay, it's been noted for consideration. I'll close for now.
