### ISSUE TITLE
Urbint, smart city

### ISSUE THREAD

**Issue by kanishka-azimi** [erkmos/haskell-companies#76]
Urbint - see job ad on their site or GitHub

Nec nz - https://nz.nec.com/en_NZ/products_solutions/smartcity/index.html - https://www.reddit.com/r/haskell/comments/8ye1h0/explaining_why_our_team_picked_haskell_and_elm/

**Comment by erkmos** [comment]
Thanks for the update! But can you please provide more information in the future, thanks! 😄
