### ISSUE TITLE
Clearwater Analytics doesn't use Haskell

### ISSUE THREAD

**Issue by JustAnotherSoftwareDeveloper** [erkmos/haskell-companies#89]
Hello, 

I work at Clearwater Analytics in Boise Idaho. Haskell isn't on our approved tech stack. I went down and asked the analysts if they used it and they were confused. I don't think anyone uses haskell.

**Comment by erkmos** [comment]
Thanks for the update. As the original source is 1 year old I guess it might have changed, I will remove the company for now
