### ISSUE TITLE
Started a similar list for purescript, with attribution

### ISSUE THREAD

**Issue by ajnsit** [erkmos/haskell-companies#91]
I started a similar list for companies that use Purescript. It currently uses pretty much the same format and blurb as this list, but I have added an attribution to this project at the top. I hope that this is acceptable. Please let me know if you would like me to change something.

The project is here -
https://github.com/ajnsit/purescript-companies

**Comment by erkmos** [comment]
Nice initiative. That's fine, good luck!

**Comment by zarelit** [comment]
@erkmos I think that people interested in companies using Haskell are likely to be interested in companies using PureScript. Would you accept a PR to add a top reference to this other list?

**Comment by erkmos** [comment]
I guess that would be ok
